import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Bar from "@/components/menu-bar/menuBar";
import { Separator } from "@/components/ui/separator";
import { Poppins } from "next/font/google";
import Head from "next/head";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "400", "900"]
});


export const metadata: Metadata = {
  title: "Shan's",
  description: "Generated by create next app",
  icons:"./pc2.ico"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-background`}>
        <div className="">
          <Bar />
        </div>
        <Separator />
        {children}
      </body>
    </html>
  );
}
