import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Bar from "@/components/menu-bar/menuBar";
import { Separator } from "@/components/ui/separator";
import { Jua } from "next/font/google";

const jua = Jua({
  subsets: ["latin"],
  weight: "400", // Jua only has one weight, 400
});


export const metadata: Metadata = {
  title: "about-me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jua.className} antialiased bg-background`}>
        <div className="">
          <Bar />
        </div>
        <Separator className="mb-5" />
        {children}
      </body>
    </html>
  );
}
